<?php
echo '<html>';
echo '<head>';
echo '<title>gallery</title>';
echo '<style>';
echo '*{margin: 0; padding: 0;}';
echo 'body';
echo '{';
echo 'background: white';
echo '}';
echo '.container';
echo '{';
echo 'width: 100%;';
echo 'height: 100%;';
echo 'padding-bottom: 50px;';
echo '';
echo '}';
echo '.trans';
echo '{';
echo 'transition: all 1s ease;';
echo '-moz-transition: all 1s ease;';
echo '-ms-transition: all 1s ease;';
echo '-o-transition: all 1s ease;';
echo '-webkit-transition: all 1s ease;';
echo '}';
echo '.top';
echo '{';
echo 'display: flex;';
echo 'width: 80vw;';
echo 'height: 80vh;';
echo 'margin-top: 10vh;';
echo 'margin-left: auto;';
echo 'margin-right: auto;';
echo 'margin-bottom: 10vh;';
echo '}';
echo '.top ul';
echo '{';
echo 'list-style: none;';
echo 'width: 100%;';
echo 'height: 100%;';
echo 'z-index: 1;';
echo 'box-sizing: border-box;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '.top ul li';
echo '{';
echo 'position: relative;';
echo 'float: left;';
echo 'width: 25%;';
echo 'height: 25%;';
echo 'overflow: hidden;';
echo '}';
echo '';
echo '.top ul li::before';
echo '{';
echo 'position: absolute;';
echo 'top: 0;';
echo 'left: 0;';
echo 'width: 100%;';
echo 'height: 100%;';
echo 'content: ';
echo 'color: white;';
echo 'opacity: 0.4;';
echo 'text-align: center;';
echo 'box-sizing: border-box;';
echo 'pointer-events: none;';
echo 'transition: all 0.5s ease;';
echo '-moz-transition: all 0.5s ease;';
echo '-ms-transition: all 0.5s ease;';
echo '-o-transition: all 0.5s ease;';
echo '-webkit-transition: all 0.5s ease;';
echo '}';
echo '.top ul li:hover::before';
echo '{';
echo 'opacity: 50;';
echo 'background-color: black;';
echo '}';
echo '.top ul li img';
echo '{';
echo 'width: 100%;';
echo 'height: auto;';
echo 'overflow: hidden;';
echo 'padding : 5px;';
echo '}';
echo '.lightbox';
echo '{';
echo 'position: fixed;';
echo 'width: 100%;';
echo 'height: 100%;';
echo 'text-align: center;';
echo 'top: 0;';
echo 'left: 0;';
echo 'background-color: rgba(0,0,0,0.75);';
echo 'z-index: 999;';
echo 'opacity: 0;';
echo 'pointer-events: none;';
echo '}';
echo '.lightbox img';
echo '{';
echo 'max-width: 90%;';
echo 'max-height: 80%;';
echo 'position: relative;';
echo 'top: -100%;';
echo '/* Transition */';
echo 'transition: all 1s ease;';
echo '-moz-transition: all 1s ease;';
echo '-ms-transition: all 1s ease;';
echo '-o-transition: all 1s ease;';
echo '-webkit-transition: all 1s ease;';
echo '}';
echo '.lightbox:target';
echo '{';
echo 'outline: none;';
echo 'top: 0;';
echo 'opacity: 1;';
echo 'pointer-events: auto;';
echo 'transition: all 1.2s ease;';
echo '-moz-transition: all 1.2s ease;';
echo '-ms-transition: all 1.2s ease;';
echo '-o-transition: all 1.2s ease;';
echo '-webkit-transition: all 1.2s ease;';
echo '}';
echo '.lightbox:target img';
echo '{';
echo 'top: 0;';
echo 'top: 50%;';
echo 'transform: translateY(-50%);';
echo '-moz-transform: translateY(-50%);';
echo '-ms-transform: translateY(-50%);';
echo '-o-transform: translateY(-50%);';
echo '-webkit-transform: translateY(-50%);';
echo '}';
echo '.back a{';
echo 'color: #000000;';
echo 'text-decoration: none;';
echo 'padding: 2px 2px ;';
echo '}';
echo '.back a:hover{';
echo 'text-decoration: none;';
echo '';
echo '}';
echo '.gallary a{';
echo 'color: #03e9f4;';
echo 'text-align :center;';
echo 'padding:0;';
echo '';
echo '}';
echo '';
echo '.lab a{';
echo 'color: #000000;';
echo 'text-align :center;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '';
echo '.republic a{';
echo 'color: #000000;';
echo 'text-align :center;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '';
echo '.picnic a{';
echo 'color: #000000;';
echo 'text-align :center;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '';
echo '.farewell a{';
echo 'color: #000000;';
echo 'text-align :center;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '';
echo '.fresher a{';
echo 'color: #000000;';
echo 'text-align :center;';
echo 'padding-bottom:20px;';
echo '';
echo '}';
echo '';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="back">';
echo '<a href="dashboard.php">';
echo '<h3>< Back</h3></a></div>';
echo '<div class="gallary">';
echo '<a href="#">';
echo '<h1>GALLARY</h1></a></div>';
echo '';
echo '';

echo '<div class="container">';
echo '<div class="top">';
echo '<ul>';
echo '<div class="lab">';
echo '<a href="#">';
echo '<h2>Computer Lab</h2></a></div><br>';
echo '';
echo '';
echo '<li><a href="#img_1"><img src="images\computerlab.jpg"></a></li>';
echo '<li><a href="#img_2"><img src="images\computerlab1.jpg"></a></li>';
echo '<li><a href="#img_3"><img src="images\computerlab2.jpg"></a></li>';
echo '<li><a href="#img_4"><img src="images\computerlab3.jpg"></a></li><br><br><br><br>';
echo '';
echo '<div class="republic">';
echo '<a href="#">';
echo '<br><br><br><br><h2>Republilc Day</h2></a></div><br>';
echo '';
echo '';
echo '<li><a href="#img_5"><img src="images\republicday.jpeg"></a></li>';
echo '<li><a href="#img_6"><img src="images\republicday1.jpeg"></a></li>';
echo '<li><a href="#img_7"><img src="images\republicday2.jpeg"></a></li>';
echo '<li><a href="#img_8"><img src="images\republicday4.jpeg"></a></li>';
echo '';
echo '<div class="farewell">';
echo '<a href="#">';
echo '<br><br><br><br><br><br><br><h2>Farewell Party 2024</h2></a></div><br>';
echo '';
echo '';
echo '<li><a href="#img_9"><img src="images\farewellparty.jpg"></a></li>';
echo '<li><a href="#img_10"><img src="images\farewellparty1.jpg"></a></li>';
echo '<li><a href="#img_11"><img src="images\farewellparty2.jpg"></a></li>';
echo '<li><a href="#img_12"><img src="images\farewellparty3.jpg"></a></li>';
echo '<li><a href="#img_13"><img src="images\farewellparty4.jpg"></a></li>';
echo '<li><a href="#img_14"><img src="images\farewellparty5.jpg"></a></li>';
echo '<li><a href="#img_15"><img src="images\farewellparty7.jpg"></a></li>';
echo '<li><a href="#img_16"><img src="images\farewellparty8.jpg"></a></li>';
echo '';
echo '<div class="picnic">';
echo '<a href="#">';
echo '<br><br><br><br><br><h2>Picnic</h2></a></div><br>';
echo '';
echo '';
echo '<li><a href="#img_17"><img src="images\picnic.jpeg"></a></li>';
echo '<li><a href="#img_18"><img src="images\picnic1.jpeg"></a></li>';
echo '<li><a href="#img_19"><img src="images\picnic2.jpeg"></a></li>';
echo '<li><a href="#img_20"><img src="images\picnic3.jpeg"></a></li>';
echo '<li><a href="#img_21"><img src="images\picnic5.jpeg"></a></li>';
echo '<li><a href="#img_22"><img src="images\picnic6.jpeg"></a></li>';
echo '<li><a href="#img_23"><img src="images\picnic7.jpeg"></a></li>';
echo '<li><a href="#img_24"><img src="images\picnic13.jpeg"></a></li>';
echo '<li><a href="#img_25"><img src="images\picnic15.jpeg"></a></li>';
echo '<li><a href="#img_26"><img src="images\picnic17.jpeg"></a></li>';
echo '<li><a href="#img_27"><img src="images\picnic18.jpeg"></a></li>';
echo '<li><a href="#img_28"><img src="images\picnic20.jpeg"></a></li>';
echo '';
echo '<div class="fresher">';
echo '<a href="#">';
echo '<br><br><br><br><br><h2>Fresher Party 2023</h2></a></div><br>';
echo '';
echo '';
echo '<li><a href="#img_29"><img src="images\fresherparty.jpg"></a></li>';
echo '<li><a href="#img_30"><img src="images\fresherparty1.jpg"></a></li>';
echo '<li><a href="#img_31"><img src="images\fresherparty2.jpg"></a></li>';
echo '<li><a href="#img_32"><img src="images\fresherparty3.jpg"></a></li>';
echo '<li><a href="#img_33"><img src="images\fresherparty4.jpg"></a></li>';
echo '<li><a href="#img_34"><img src="images\fresherparty5.jpg"></a></li>';
echo '<li><a href="#img_35"><img src="images\fresherparty6.jpg"></a></li>';
echo '<li><a href="#img_36"><img src="images\fresherparty7.jpg"></a></li>';
echo '';
echo '</ul>';
echo '<a href="#_1" class="lightbox trans" id="img_1"><img src="images\computerlab.jpg"></a>';
echo '<a href="#_2" class="lightbox trans" id="img_2"><img src="images\computerlab1.jpg"></a>';
echo '<a href="#_3" class="lightbox trans" id="img_3"><img src="images\computerlab2.jpg"></a>';
echo '<a href="#_4" class="lightbox trans" id="img_4"><img src="images\computerlab3.jpg"></a>';
echo '';
echo '<a href="#_5" class="lightbox trans" id="img_5"><img src="images\republicday.jpeg"></a>';
echo '<a href="#_6" class="lightbox trans" id="img_6"><img src="images\republicday1.jpeg"></a>';
echo '<a href="#_7" class="lightbox trans" id="img_7"><img src="images\republicday2.jpeg"></a>';
echo '<a href="#_8" class="lightbox trans" id="img_8"><img src="images\republicday4.jpeg"></a>';
echo '';
echo '<a href="#_9" class="lightbox trans" id="img_9"><img src="images\farewellparty.jpg"></a>';
echo '<a href="#_10" class="lightbox trans" id="img_10"><img src="images\farewellparty1.jpg"></a>';
echo '<a href="#_11" class="lightbox trans" id="img_11"><img src="images\farewellparty2.jpg"></a>';
echo '<a href="#_12" class="lightbox trans" id="img_12"><img src="images\farewellparty3.jpg"></a>';
echo '<a href="#_13" class="lightbox trans" id="img_13"><img src="images\farewellparty4.jpg"></a>';
echo '<a href="#_14" class="lightbox trans" id="img_14"><img src="images\farewellparty5.jpg"></a>';
echo '<a href="#_15" class="lightbox trans" id="img_15"><img src="images\farewellparty7.jpg"></a>';
echo '<a href="#_16" class="lightbox trans" id="img_16"><img src="images\farewellparty8.jpg"></a>';
echo '';
echo '<a href="#_17" class="lightbox trans" id="img_17"><img src="images\picnic.jpeg"></a>';
echo '<a href="#_18" class="lightbox trans" id="img_18"><img src="images\picnic1.jpeg"></a>';
echo '<a href="#_19" class="lightbox trans" id="img_19"><img src="images\picnic2.jpeg"></a>';
echo '<a href="#_20" class="lightbox trans" id="img_20"><img src="images\picnic3.jpeg"></a>';
echo '<a href="#_21" class="lightbox trans" id="img_21"><img src="images\picnic5.jpeg"></a>';
echo '<a href="#_22" class="lightbox trans" id="img_22"><img src="images\picnic6.jpeg"></a>';
echo '<a href="#_23" class="lightbox trans" id="img_23"><img src="images\picnic7.jpeg"></a>';
echo '<a href="#_24" class="lightbox trans" id="img_24"><img src="images\picnic13.jpeg"></a>';
echo '<a href="#_25" class="lightbox trans" id="img_25"><img src="images\picnic15.jpeg"></a>';
echo '<a href="#_26" class="lightbox trans" id="img_26"><img src="images\picnic17.jpeg"></a>';
echo '<a href="#_27" class="lightbox trans" id="img_27"><img src="images\picnic18.jpeg"></a>';
echo '<a href="#_28" class="lightbox trans" id="img_28"><img src="images\picnic20.jpeg"></a>';
echo '';
echo '<a href="#_29" class="lightbox trans" id="img_29"><img src="images\fresherparty.jpg"></a>';
echo '<a href="#_30" class="lightbox trans" id="img_30"><img src="images\fresherparty1.jpg"></a>';
echo '<a href="#_31" class="lightbox trans" id="img_31"><img src="images\fresherparty2.jpg"></a>';
echo '<a href="#_32" class="lightbox trans" id="img_32"><img src="images\fresherparty3.jpg"></a>';
echo '<a href="#_33" class="lightbox trans" id="img_33"><img src="images\fresherparty4.jpg"></a>';
echo '<a href="#_34" class="lightbox trans" id="img_34"><img src="images\fresherparty5.jpg"></a>';
echo '<a href="#_35" class="lightbox trans" id="img_35"><img src="images\fresherparty6.jpg"></a>';
echo '<a href="#_36" class="lightbox trans" id="img_36"><img src="images\fresherparty7.jpg"></a>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>